openapi: 3.1.0
info:
  title: FantasyHub
  version: "1.0.0"
  description: |
    Petite API perso exposant, via Apps Script, les données Google Sheets :
    • **Rosters** (effectifs Sleeper)  
    • **KTC**     (valeurs KeepTradeCut)

servers:
  - url: https://script.google.com/macros/s/AKfycbxtYKZMecEpG8KdN1JzJUk6MFpmcSgHCF6leAgRel1mkkyEXe_ymGH16ohdHWGTqI9g/exec

paths:
  /:
    get:
      operationId: getSheet            # ← identifiant OBLIGATOIRE
      summary: Read a sheet tab
      description: |
        Retourne le contenu d’un onglet (`Rosters` ou `KTC`) au format JSON
        (par défaut) ou CSV.
      parameters:
        - in: query
          name: sheet
          description: Onglet à lire (défaut : **Rosters**)
          required: false
          schema:
            type: string
            enum: [Rosters, KTC]
        - in: query
          name: fmt
          description: Format de sortie (défaut : **json**)
          required: false
          schema:
            type: string
            enum: [json, csv]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array            # ← tableau de lignes
                items:
                  type: object
                  additionalProperties: true
            text/csv:
              schema:
                type: string
        "400":
          description: Bad request (paramètre manquant ou invalide)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Erreur interne Apps Script
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
