openapi: 3.0.1            # 3.0.1 est 100 % supporté par le builder
info:
  title: FantasyHub
  version: "1.0.0"
  description: |
    Petite API perso qui expose, via Apps Script, les données Google Sheets  
    – onglet **Rosters** (effectifs Sleeper) ou **KTC** (valeurs KeepTradeCut).

servers:
  - url: https://script.google.com/macros/s/AKfycbxtYKZMecEpG8KdN1JzJUk6MFpmcSgHCF6leAgRel1mkkyEXe_ymGH16ohdHWGtqI9g/exec

paths:
  /:
    get:
      operationId: getSheet            # ← requis par le builder
      summary: Read a sheet tab
      description: |
        Retourne le contenu d’un onglet (`Rosters` ou `KTC`) au format **JSON**  
        (par défaut) ou **CSV**.
      parameters:
        - in: query
          name: sheet
          description: Onglet à lire. Par défaut **Rosters**.
          required: false
          schema:
            type: string
            enum: [Rosters, KTC]
        - in: query
          name: fmt
          description: Format de sortie (`json` ou `csv`). Par défaut **json**.
          required: false
          schema:
            type: string
            enum: [json, csv]
      responses:
        "200":
          description: Données récupérées
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties: true
            text/csv:
              schema:
                type: string
        "400":
          description: Mauvaise requête
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
