openapi: 3.1.0
info:
  title: FantasyHub
  version: "1.0.0"
  description: >
    API Apps Script exposant deux onglets Google Sheets :
    - Rosters  (Sleeper rosters)
    - KTC      (KeepTradeCut superflex values)

servers:
  - url: https://script.google.com/macros/s/AKfycbxtYKZMecEpG8KdN1JzJUk6MFpmcSgHCF6leAgRel1mkkyEXe_ymGH16ohdHWGTqI9g/exec

paths:
  /:
    get:
      operationId: getSheet          # identifiant requis
      summary: Read a sheet tab
      parameters:
        - in: query
          name: sheet
          description: Sheet tab (Rosters par défaut)
          required: false
          schema:
            type: string
            enum: [Rosters, KTC]
            default: Rosters
        - in: query
          name: fmt
          description: Output format (json par défaut)
          required: false
          schema:
            type: string
            enum: [json, csv]
            default: json
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array          # tableau de lignes
                items:
                  type: object
                  additionalProperties: true
            text/csv:
              schema:
                type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
